repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Specify the latest stable version of Flake8
    hooks:
      - id: flake8
        args: [--max-line-length=120]  # Set your desired Flake8 configurations

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
