name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version here

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run static code analysis (e.g., Flake8)
      - name: Run Flake8 (code quality check)
        run: |
          pip install flake8
          flake8 .

      # Step 5: Run security checks (e.g., Bandit)
      - name: Run Security Scan (Bandit)
        run: |
          pip install bandit
          bandit -r . 

      # Step 6: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout the code again in the deploy job
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Deploy to your server or hosting platform
      - name: Deploy to Server (e.g., SSH)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@your-server-ip << EOF
          cd /home/ubuntu/myapp
          git pull origin main
          # If using a virtual environment, activate it
          source venv/bin/activate
          pip install -r requirements.txt
          # Run any migration or startup command
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
          EOF
